"""empty message

Revision ID: 0e0f406591d5
Revises: d03c3abc005d
Create Date: 2024-10-22 13:14:01.354103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e0f406591d5'
down_revision: Union[str, None] = 'd03c3abc005d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('config', sa.Column('position_role_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('config', 'position_role_id')
    # ### end Alembic commands ###
