"""empty message

Revision ID: 213a40388bf3
Revises: 8ba212e14608
Create Date: 2024-04-25 23:06:32.461294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '213a40388bf3'
down_revision: Union[str, None] = '8ba212e14608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto_response_messages', 'case_sensitive')
    op.drop_column('auto_response_messages', 'enabled')
    op.drop_column('auto_response_messages', 'ephemeral')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto_response_messages', sa.Column('ephemeral', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('auto_response_messages', sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('auto_response_messages', sa.Column('case_sensitive', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
