"""empty message

Revision ID: 35b1f0974ab3
Revises: 0e0f406591d5
Create Date: 2024-10-25 19:47:50.355536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "35b1f0974ab3"
down_revision: Union[str, None] = "0e0f406591d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

LEVELS_AND_XP = {  # credit's for this goes to the mee6 developers as we use the same exp values as them
    0: 0,
    1: 100,
    2: 255,
    3: 475,
    4: 770,
    5: 1_150,
    6: 1_625,
    7: 2_205,
    8: 2_900,
    9: 3_720,
    10: 4_675,
    11: 5_775,
    12: 7_030,
    13: 8_450,
    14: 10_045,
    15: 11_825,
    16: 13_800,
    17: 15_980,
    18: 18_375,
    19: 20_995,
    20: 23_850,
    21: 26_950,
    22: 30_305,
    23: 33_925,
    24: 37_820,
    25: 42_000,
    26: 46_475,
    27: 51_255,
    28: 56_350,
    29: 61_770,
    30: 67_525,
    31: 73_625,
    32: 80_080,
    33: 86_900,
    34: 94_095,
    35: 101_675,
    36: 109_650,
    37: 118_030,
    38: 126_825,
    39: 136_045,
    40: 145_700,
    41: 155_800,
    42: 166_355,
    43: 177_375,
    44: 188_870,
    45: 200_850,
    46: 213_325,
    47: 226_305,
    48: 239_800,
    49: 253_820,
    50: 268_375,
    51: 283_475,
    52: 299_130,
    53: 315_350,
    54: 332_145,
    55: 349_525,
    56: 367_500,
    57: 386_080,
    58: 405_275,
    59: 425_095,
    60: 445_550,
    61: 466_650,
    62: 488_405,
    63: 510_825,
    64: 533_920,
    65: 557_700,
    66: 582_175,
    67: 607_355,
    68: 633_250,
    69: 659_870,
    70: 687_225,
    71: 715_325,
    72: 744_180,
    73: 773_800,
    74: 804_195,
    75: 835_375,
    76: 867_350,
    77: 900_130,
    78: 933_725,
    79: 968_145,
    80: 1_003_400,
    81: 1_039_500,
    82: 1_076_455,
    83: 1_114_275,
    84: 1_152_970,
    85: 1_192_550,
    86: 1_233_025,
    87: 1_274_405,
    88: 1_316_700,
    89: 1_359_920,
    90: 1_404_075,
    91: 1_449_175,
    92: 1_495_230,
    93: 1_542_250,
    94: 1_590_245,
    95: 1_639_225,
    96: 1_689_200,
    97: 1_740_180,
    98: 1_792_175,
    99: 1_845_195,
    100: 1_899_250,
    101: 1_954_350,
    102: 2_010_505,
    103: 2_067_725,
    104: 2_126_020,
    105: 2_185_400,
    106: 2_245_875,
    107: 2_307_455,
    108: 2_370_150,
    109: 2_433_970,
    110: 2_498_925,
    111: 2_565_025,
    112: 2_632_280,
    113: 2_700_700,
    114: 2_770_295,
    115: 2_841_075,
    116: 2_913_050,
    117: 2_986_230,
    118: 3_060_625,
    119: 3_136_245,
    120: 3_213_100,
    121: 3_291_200,
    122: 3_370_555,
    123: 3_451_175,
    124: 3_533_070,
    125: 3_616_250,
    126: 3_700_725,
    127: 3_786_505,
    128: 3_873_600,
    129: 3_962_020,
    130: 4_051_775,
    131: 4_142_875,
    132: 4_235_330,
    133: 4_329_150,
    134: 4_424_345,
    135: 4_520_925,
    136: 4_618_900,
    137: 4_718_280,
    138: 4_819_075,
    139: 4_921_295,
    140: 5_024_950,
    141: 5_130_050,
    142: 5_236_605,
    143: 5_344_625,
    144: 5_454_120,
    145: 5_565_100,
    146: 5_677_575,
    147: 5_791_555,
    148: 5_907_050,
    149: 6_024_070,
    150: 6_142_625,
}


def upgrade() -> None:
    # Add the new column for storing the total XP
    op.add_column("levels", sa.Column("total_xp", sa.Integer(), nullable=True))

    # Connection to execute SQL
    conn = op.get_bind()

    # Fetch all users with their levels and current XP
    results = conn.execute(sa.text("SELECT id, level, xp FROM levels")).fetchall()

    # Compute total XP for each user based on their level and XP
    for row in results:
        user_id, level, current_xp = row
        # Calculate total XP by summing up the XP for all levels up to the user's level
        total_xp = sum(LEVELS_AND_XP[lvl] for lvl in range(1, level + 1)) + current_xp

        # Update each user's total_xp in the database
        conn.execute(
            sa.text("UPDATE levels SET total_xp = :total_xp WHERE id = :id"),
            {"total_xp": total_xp, "id": user_id},
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("levels", "total_xp")
    # ### end Alembic commands ###
