"""empty message

Revision ID: 5fc50a2211f8
Revises: 35b1f0974ab3
Create Date: 2024-10-26 20:42:11.117773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fc50a2211f8'
down_revision: Union[str, None] = '35b1f0974ab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('levels', 'xp')
    op.drop_column('levels', 'level')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('levels', sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('levels', sa.Column('xp', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
