"""empty message

Revision ID: 873bf42cf67e
Revises: 6587051215f2
Create Date: 2023-12-28 19:57:21.714141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '873bf42cf67e'
down_revision: Union[str, None] = '6587051215f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'commands', ['guild_id', 'command'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'commands', type_='unique')
    # ### end Alembic commands ###
