"""empty message

Revision ID: 8ba212e14608
Revises: 873bf42cf67e
Create Date: 2024-04-25 22:33:33.652474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ba212e14608'
down_revision: Union[str, None] = '873bf42cf67e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_response_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_ids', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('regex_strings', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('strings', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('case_sensitive', sa.Boolean(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('ephemeral', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auto_response_messages')
    # ### end Alembic commands ###
