"""empty message

Revision ID: d03c3abc005d
Revises: aa463358ce38
Create Date: 2024-10-22 00:34:53.263372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd03c3abc005d'
down_revision: Union[str, None] = 'aa463358ce38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('config', sa.Column('min_required_lvl', sa.Integer(), nullable=True))
    op.drop_column('custom_roles', 'min_required_lvl')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_roles', sa.Column('min_required_lvl', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('config', 'min_required_lvl')
    # ### end Alembic commands ###
